#!/bin/bash -e
version="0.6.0"
wget https://github.com/docker/docker-credential-helpers/releases/download/v$version/docker-credential-pass-v$version-amd64.tar.gz
tar -xf docker-credential-pass-v$version-amd64.tar.gz
echo "Installing to /usr/bin/docker-credential-pass"
sudo mv ./docker-credential-pass /usr/bin
rm docker-credential-pass-v$version-amd64.tar.gz

